### ISSUE TITLE
Discussion Thread

### ISSUE THREAD

**Issue by Liftoff-Studios** [Khan-Academy-Coder-s-Group/Discussion-Repo#1]
**### Thread for Discussion**

**Comment by Liftoff-Studios** [comment]
Hey Everyone !!

**Comment by Liftoff-Studios** [comment]
Everyone Pls Try to Inform other KA people on Github about this :)

**Comment by ghost** [comment]
Hey! Thanks for inviting me! This is kinda early, but should we move to repl.it? Seriously, it is so much better than Github. Same free hosting services, a better editor, node.js server, and you can code in tons of languages. 
Just a little introduction, I'm Coder's Digest 911, and my skills are in full stack web development. I can handle the backend to all of our projects.
Can't wait to see where this goes!

**Comment by Liftoff-Studios** [comment]
Hey there @Coders-Digest911 

The reason I made it here because i'm only 13 and my parents have restricted me to github only 
I'm Really Sorry but I can go on repel.it
If you want the final project can be hosted on repl.it

Really Sorry :(
But really hope this gets far :)

**Comment by ghost** [comment]
Understandable!
Can't wait to develop something!

**Comment by Liftoff-Studios** [comment]
Yay !! 
Let's get the party started !!

**Comment by Liftoff-Studios** [comment]
Should we create a homepage ??

**Comment by Voldemort271** [comment]
You could just set up Discussions instead of opening an issue lol

**Comment by Liftoff-Studios** [comment]
How do you do that ?? Lol I didnt know :)

**Comment by Liftoff-Studios** [comment]
Ok opened one
Pls report there
